// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DailyRecord struct {
	Date          string  `json:"date"`
	TradingVolume float64 `json:"tradingVolume"`
	TradingPrice  float64 `json:"tradingPrice"`
	OpenPrice     float64 `json:"openPrice"`
	HighestPrice  float64 `json:"highestPrice"`
	LowestPrice   float64 `json:"lowestPrice"`
	ClosePrice    float64 `json:"closePrice"`
	PriceDiff     float64 `json:"priceDiff"`
	TransAmount   float64 `json:"transAmount"`
}

type NewRecord struct {
	Code          string  `json:"code"`
	Name          string  `json:"name"`
	Date          string  `json:"date"`
	TradingVolume float64 `json:"tradingVolume"`
	TradingPrice  float64 `json:"tradingPrice"`
	OpenPrice     float64 `json:"openPrice"`
	HighestPrice  float64 `json:"highestPrice"`
	LowestPrice   float64 `json:"lowestPrice"`
	ClosePrice    float64 `json:"closePrice"`
	PriceDiff     float64 `json:"priceDiff"`
	TransAmount   float64 `json:"transAmount"`
}

type NewStock struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type Stock struct {
	Code             string         `json:"code"`
	Name             string         `json:"name"`
	HistoricalRecord []*DailyRecord `json:"historicalRecord"`
}
